use gl;

#[inline]
pub fn attrib_pointers(gl: &gl::Glw, data: &::render::buffer::Layout) {
    let stride = data.items.iter()
        .map(|i| i.bytes())
        .sum();

    let mut offset = 0;

    for item in data.items.iter() {
        unsafe {
            use render::buffer::Format::*;

            match item.format {
                i8 => gl.VertexAttribIPointer(item.index,
                                              1,
                                              gl::BYTE,
                                              stride,
                                              offset as *const gl::types::GLvoid),
                i8_i8 => gl.VertexAttribIPointer(item.index,
                                                 2,
                                                 gl::BYTE,
                                                 stride,
                                                 offset as *const gl::types::GLvoid),
                i8_i8_i8 => gl.VertexAttribIPointer(item.index,
                                                    3,
                                                    gl::BYTE,
                                                    stride,
                                                    offset as *const gl::types::GLvoid),
                i8_i8_i8_i8 => gl.VertexAttribIPointer(item.index,
                                                       4,
                                                       gl::BYTE,
                                                       stride,
                                                       offset as *const gl::types::GLvoid),

                i8_float => gl.VertexAttribPointer(item.index,
                                                   1,
                                                   gl::BYTE,
                                                   gl::TRUE,
                                                   stride,
                                                   offset as *const gl::types::GLvoid),
                i8_i8_float => gl.VertexAttribPointer(item.index,
                                                      2,
                                                      gl::BYTE,
                                                      gl::TRUE,
                                                      stride,
                                                      offset as *const gl::types::GLvoid),
                i8_i8_i8_float => gl.VertexAttribPointer(item.index,
                                                         3,
                                                         gl::BYTE,
                                                         gl::TRUE,
                                                         stride,
                                                         offset as *const gl::types::GLvoid),
                i8_i8_i8_i8_float => gl.VertexAttribPointer(item.index,
                                                            4,
                                                            gl::BYTE,
                                                            gl::TRUE,
                                                            stride,
                                                            offset as *const gl::types::GLvoid),

                i16 => gl.VertexAttribIPointer(item.index,
                                               1,
                                               gl::SHORT,
                                               stride,
                                               offset as *const gl::types::GLvoid),
                i16_i16 => gl.VertexAttribIPointer(item.index,
                                                   2,
                                                   gl::SHORT,
                                                   stride,
                                                   offset as *const gl::types::GLvoid),
                i16_i16_i16 => gl.VertexAttribIPointer(item.index,
                                                       3,
                                                       gl::SHORT,
                                                       stride,
                                                       offset as *const gl::types::GLvoid),
                i16_i16_i16_i16 => gl.VertexAttribIPointer(item.index,
                                                           4,
                                                           gl::SHORT,
                                                           stride,
                                                           offset as *const gl::types::GLvoid),

                i16_float => gl.VertexAttribPointer(item.index,
                                                    1,
                                                    gl::SHORT,
                                                    gl::TRUE,
                                                    stride,
                                                    offset as *const gl::types::GLvoid),
                i16_i16_float => gl.VertexAttribPointer(item.index,
                                                        2,
                                                        gl::SHORT,
                                                        gl::TRUE,
                                                        stride,
                                                        offset as *const gl::types::GLvoid),
                i16_i16_i16_float => gl.VertexAttribPointer(item.index,
                                                            3,
                                                            gl::SHORT,
                                                            gl::TRUE,
                                                            stride,
                                                            offset as *const gl::types::GLvoid),
                i16_i16_i16_i16_float => gl.VertexAttribPointer(item.index,
                                                                4,
                                                                gl::SHORT,
                                                                gl::TRUE,
                                                                stride,
                                                                offset as *const gl::types::GLvoid),

                i32 => gl.VertexAttribIPointer(item.index,
                                               1,
                                               gl::INT,
                                               stride,
                                               offset as *const gl::types::GLvoid),
                i32_i32 => gl.VertexAttribIPointer(item.index,
                                                   2,
                                                   gl::INT,
                                                   stride,
                                                   offset as *const gl::types::GLvoid),
                i32_i32_i32 => gl.VertexAttribIPointer(item.index,
                                                       3,
                                                       gl::INT,
                                                       stride,
                                                       offset as *const gl::types::GLvoid),
                i32_i32_i32_i32 => gl.VertexAttribIPointer(item.index,
                                                           4,
                                                           gl::INT,
                                                           stride,
                                                           offset as *const gl::types::GLvoid),

                i32_float => gl.VertexAttribPointer(item.index,
                                                    1,
                                                    gl::INT,
                                                    gl::TRUE,
                                                    stride,
                                                    offset as *const gl::types::GLvoid),
                i32_i32_float => gl.VertexAttribPointer(item.index,
                                                        2,
                                                        gl::INT,
                                                        gl::TRUE,
                                                        stride,
                                                        offset as *const gl::types::GLvoid),
                i32_i32_i32_float => gl.VertexAttribPointer(item.index,
                                                            3,
                                                            gl::INT,
                                                            gl::TRUE,
                                                            stride,
                                                            offset as *const gl::types::GLvoid),
                i32_i32_i32_i32_float => gl.VertexAttribPointer(item.index,
                                                                4,
                                                                gl::INT,
                                                                gl::TRUE,
                                                                stride,
                                                                offset as *const gl::types::GLvoid),

                u8 => gl.VertexAttribIPointer(item.index,
                                              1,
                                              gl::UNSIGNED_BYTE,
                                              stride,
                                              offset as *const gl::types::GLvoid),
                u8_u8 => gl.VertexAttribIPointer(item.index,
                                                 2,
                                                 gl::UNSIGNED_BYTE,
                                                 stride,
                                                 offset as *const gl::types::GLvoid),
                u8_u8_u8 => gl.VertexAttribIPointer(item.index,
                                                    3,
                                                    gl::UNSIGNED_BYTE,
                                                    stride,
                                                    offset as *const gl::types::GLvoid),
                u8_u8_u8_u8 => gl.VertexAttribIPointer(item.index,
                                                       4,
                                                       gl::UNSIGNED_BYTE,
                                                       stride,
                                                       offset as *const gl::types::GLvoid),

                u8_float => gl.VertexAttribPointer(item.index,
                                                   1,
                                                   gl::UNSIGNED_BYTE,
                                                   gl::TRUE,
                                                   stride,
                                                   offset as *const gl::types::GLvoid),
                u8_u8_float => gl.VertexAttribPointer(item.index,
                                                      2,
                                                      gl::UNSIGNED_BYTE,
                                                      gl::TRUE,
                                                      stride,
                                                      offset as *const gl::types::GLvoid),
                u8_u8_u8_float => gl.VertexAttribPointer(item.index,
                                                         3,
                                                         gl::UNSIGNED_BYTE,
                                                         gl::TRUE,
                                                         stride,
                                                         offset as *const gl::types::GLvoid),
                u8_u8_u8_u8_float => gl.VertexAttribPointer(item.index,
                                                            4,
                                                            gl::UNSIGNED_BYTE,
                                                            gl::TRUE,
                                                            stride,
                                                            offset as *const gl::types::GLvoid),

                u16 => gl.VertexAttribIPointer(item.index,
                                               1,
                                               gl::UNSIGNED_SHORT,
                                               stride,
                                               offset as *const gl::types::GLvoid),
                u16_u16 => gl.VertexAttribIPointer(item.index,
                                                   2,
                                                   gl::UNSIGNED_SHORT,
                                                   stride,
                                                   offset as *const gl::types::GLvoid),
                u16_u16_u16 => gl.VertexAttribIPointer(item.index,
                                                       3,
                                                       gl::UNSIGNED_SHORT,
                                                       stride,
                                                       offset as *const gl::types::GLvoid),
                u16_u16_u16_u16 => gl.VertexAttribIPointer(item.index,
                                                           4,
                                                           gl::UNSIGNED_SHORT,
                                                           stride,
                                                           offset as *const gl::types::GLvoid),

                u16_float => gl.VertexAttribPointer(item.index,
                                                    1,
                                                    gl::UNSIGNED_SHORT,
                                                    gl::TRUE,
                                                    stride,
                                                    offset as *const gl::types::GLvoid),
                u16_u16_float => gl.VertexAttribPointer(item.index,
                                                        2,
                                                        gl::UNSIGNED_SHORT,
                                                        gl::TRUE,
                                                        stride,
                                                        offset as *const gl::types::GLvoid),
                u16_u16_u16_float => gl.VertexAttribPointer(item.index,
                                                            3,
                                                            gl::UNSIGNED_SHORT,
                                                            gl::TRUE,
                                                            stride,
                                                            offset as *const gl::types::GLvoid),
                u16_u16_u16_u16_float => gl.VertexAttribPointer(item.index,
                                                                4,
                                                                gl::UNSIGNED_SHORT,
                                                                gl::TRUE,
                                                                stride,
                                                                offset as *const gl::types::GLvoid),

                u32 => gl.VertexAttribIPointer(item.index,
                                               1,
                                               gl::UNSIGNED_INT,
                                               stride,
                                               offset as *const gl::types::GLvoid),
                u32_u32 => gl.VertexAttribIPointer(item.index,
                                                   2,
                                                   gl::UNSIGNED_INT,
                                                   stride,
                                                   offset as *const gl::types::GLvoid),
                u32_u32_u32 => gl.VertexAttribIPointer(item.index,
                                                       3,
                                                       gl::UNSIGNED_INT,
                                                       stride,
                                                       offset as *const gl::types::GLvoid),
                u32_u32_u32_u32 => gl.VertexAttribIPointer(item.index,
                                                           4,
                                                           gl::UNSIGNED_INT,
                                                           stride,
                                                           offset as *const gl::types::GLvoid),

                u32_float => gl.VertexAttribPointer(item.index,
                                                    1,
                                                    gl::UNSIGNED_INT,
                                                    gl::TRUE,
                                                    stride,
                                                    offset as *const gl::types::GLvoid),
                u32_u32_float => gl.VertexAttribPointer(item.index,
                                                        2,
                                                        gl::UNSIGNED_INT,
                                                        gl::TRUE,
                                                        stride,
                                                        offset as *const gl::types::GLvoid),
                u32_u32_u32_float => gl.VertexAttribPointer(item.index,
                                                            3,
                                                            gl::UNSIGNED_INT,
                                                            gl::TRUE,
                                                            stride,
                                                            offset as *const gl::types::GLvoid),
                u32_u32_u32_u32_float => gl.VertexAttribPointer(item.index,
                                                                4,
                                                                gl::UNSIGNED_INT,
                                                                gl::TRUE,
                                                                stride,
                                                                offset as *const gl::types::GLvoid),

                f16 => gl.VertexAttribPointer(item.index,
                                              1,
                                              gl::HALF_FLOAT,
                                              gl::TRUE,
                                              stride,
                                              offset as *const gl::types::GLvoid),
                f16_f16 => gl.VertexAttribPointer(item.index,
                                                  2,
                                                  gl::HALF_FLOAT,
                                                  gl::TRUE,
                                                  stride,
                                                  offset as *const gl::types::GLvoid),
                f16_f16_f16 => gl.VertexAttribPointer(item.index,
                                                      3,
                                                      gl::HALF_FLOAT,
                                                      gl::TRUE,
                                                      stride,
                                                      offset as *const gl::types::GLvoid),
                f16_f16_f16_f16 => gl.VertexAttribPointer(item.index,
                                                          4,
                                                          gl::HALF_FLOAT,
                                                          gl::TRUE,
                                                          stride,
                                                          offset as *const gl::types::GLvoid),

                f32 => gl.VertexAttribPointer(item.index,
                                              1,
                                              gl::FLOAT,
                                              gl::TRUE,
                                              stride,
                                              offset as *const gl::types::GLvoid),
                f32_f32 => gl.VertexAttribPointer(item.index,
                                                  2,
                                                  gl::FLOAT,
                                                  gl::TRUE,
                                                  stride,
                                                  offset as *const gl::types::GLvoid),
                f32_f32_f32 => gl.VertexAttribPointer(item.index,
                                                      3,
                                                      gl::FLOAT,
                                                      gl::TRUE,
                                                      stride,
                                                      offset as *const gl::types::GLvoid),
                f32_f32_f32_f32 => gl.VertexAttribPointer(item.index,
                                                          4,
                                                          gl::FLOAT,
                                                          gl::TRUE,
                                                          stride,
                                                          offset as *const gl::types::GLvoid),

                f64 => gl.VertexAttribLPointer(item.index,
                                               1,
                                               gl::DOUBLE,
                                               stride,
                                               offset as *const gl::types::GLvoid),
                f64_f64 => gl.VertexAttribLPointer(item.index,
                                                   2,
                                                   gl::DOUBLE,
                                                   stride,
                                                   offset as *const gl::types::GLvoid),
                f64_f64_f64 => gl.VertexAttribLPointer(item.index,
                                                       3,
                                                       gl::DOUBLE,
                                                       stride,
                                                       offset as *const gl::types::GLvoid),
                f64_f64_f64_f64 => gl.VertexAttribLPointer(item.index,
                                                           4,
                                                           gl::DOUBLE,
                                                           stride,
                                                           offset as *const gl::types::GLvoid),

                i2_i10_i10_i10_rev => gl.VertexAttribPointer(item.index,
                                                             4,
                                                             gl::INT_2_10_10_10_REV,
                                                             gl::FALSE,
                                                             stride,
                                                             offset as *const gl::types::GLvoid),
                u2_u10_u10_u10_rev => gl.VertexAttribPointer(item.index,
                                                             4,
                                                             gl::UNSIGNED_INT_2_10_10_10_REV,
                                                             gl::FALSE,
                                                             stride,
                                                             offset as *const gl::types::GLvoid),
                u10_u11_u11_rev => gl.VertexAttribPointer(item.index,
                                                          3,
                                                          gl::UNSIGNED_INT_10F_11F_11F_REV,
                                                          gl::FALSE,
                                                          stride,
                                                          offset as *const gl::types::GLvoid),

                i2_i10_i10_i10_rev_float => gl.VertexAttribPointer(item.index,
                                                                   4,
                                                                   gl::INT_2_10_10_10_REV,
                                                                   gl::TRUE,
                                                                   stride,
                                                                   offset as *const gl::types::GLvoid),
                u2_u10_u10_u10_rev_float => gl.VertexAttribPointer(item.index,
                                                                   4,
                                                                   gl::UNSIGNED_INT_2_10_10_10_REV,
                                                                   gl::TRUE,
                                                                   stride,
                                                                   offset as *const gl::types::GLvoid),
                u10_u11_u11_rev_float => gl.VertexAttribPointer(item.index,
                                                                3,
                                                                gl::UNSIGNED_INT_10F_11F_11F_REV,
                                                                gl::TRUE,
                                                                stride,
                                                                offset as *const gl::types::GLvoid),
            };

            gl.EnableVertexAttribArray(item.index);
        }

        offset += item.bytes();
    }
}